### ISSUE TITLE
Failed to install sklearn while installing requirements

### ISSUE THREAD

**Issue by Geravant** [jetbrains-academy/gateway-to-pandas#28]
A user report: "this error comes up when I open the pandas course, I assume it's an issue with the way its named in the dependencies?"

![image](https://github.com/jetbrains-academy/gateway-to-pandas/assets/29254650/5cfad60b-1e48-4607-9992-bef00b624bef)

**Comment by DaniilBogdanovJB** [comment]
The issue was successfully reproduced, created a [ticker on YouTrack](https://youtrack.jetbrains.com/issue/EDC-880/Gateway-to-Pandas-requirements.txt-contains-deprecated-package)

**Comment by Geravant** [comment]
@avalur , we have encountered the same issue while deploying on remote dev, please, take a look

**Comment by avalur** [comment]
Thanks a lot! Fix it here: https://github.com/jetbrains-academy/gateway-to-pandas/pull/29
